### ISSUE TITLE
Error: Return value of nickdnk\ZeroBounce\Result::getDomain() must be of the type string, null returned	

### ISSUE THREAD

**Issue by jozefgrencik** [nickdnk/zerobounce-php#1]
Hi, there is small bug:

**Error: Return value of nickdnk\ZeroBounce\Result::getDomain() must be of the type string, null returned**

Example mail address: 'disposable@example.com'

You need to change line:
public function getDomain(): string
to
public function getDomain(): ?string

Thank you.

**Comment by nickdnk** [comment]
Fixed and released as 1.0.3. I have no idea how the domain can be null for a valid e-mail, however, but that is the fault of ZeroBounce.
